### ISSUE TITLE
Composer: password prompt unprotected

### ISSUE THREAD

**Issue by lauripiisang** [iMega/docker-images#2]
I ran into an issue where passwords were being prompted without secure entry for private repos.
I researched it, found that the issue was that composer's secure shell entry didn't support "sh", only one of `[bash, ksh, zsh, csh]`. I fixed that compatibility problem in https://github.com/Seldaek/cli-prompt/pull/2 , It was merged to composer/composer master in https://github.com/composer/composer/issues/5209 . 

So, to fix the input problem for your (very nice and minimal, btw!) docker images, you should either:

1) Make a bleeding edge composer image based on composer "master" / https://github.com/composer/composer/commit/b01829235729d0f723140bb80c9447478fdae013
2) Add a symlink into `RUN` section that makes a symlink `ln -s /bin/sh /bin/bash` (I think this works better as a quick hack until composer releases the fixed version). You can use bash/ksh/zsh as the alias (csh has different implementation, do not use!), up to you. As long as you add it as the last 'run' operation, there shouldn't be any compatibility issues.

**Comment by lauripiisang** [comment]
Added PR for the latest version. Backport it to the older ones as you see fit.

**Comment by iMega** [comment]
Thanks you!

**Comment by iMega** [comment]
Fix on imega/composer:2.1.1
