### ISSUE TITLE
alpine php7 packages are no more available on the testing repository 

### ISSUE THREAD

**Issue by eviweb** [iMega/docker-images#6]
Hi,

alpine php7 packages have been moved to the community repository and are now available at:
http://dl-cdn.alpinelinux.org/alpine/edge/community

**Comment by iMega** [comment]
Thanks a lot, If you are talking about the composer, I moved it here https://github.com/imega-docker/composer.

**Comment by eviweb** [comment]
In fact I built a php 7 image using the base builder image 1.1.3 from this repo.
I didn't notice it has also moved and has been updated...
Very nice job.
thanks

**Comment by iMega** [comment]
You are welcom! In the future, please feel free to file an issue on GitHub to report bugs or ask for help :)
